### PR TITLE
264 annotation index

### PR DESCRIPTION
**Pull request by eharkins**

### CODE REVIEW

**Comment by metasoarous** [comment]
@eharkins Is it worth waiting on this if @psathyrella puts together a more stand-alone version of the lbi/lbr computations?

**Comment by eharkins** [comment]
@metasoarous Ok with me; I think Duncan is the only one in any hurry to get LB data run through cft at the moment unless this is blocking some data build or other work for us?

**Comment by eharkins** [comment]
@metasoarous This actually needs to wait because the code I added to parse the cluster annotation is not complete regardless of LB stuff.

**Comment by eharkins** [comment]
@metasoarous using partis get-tree-metrics.py now instead of annotate, which was the goal I believe. Will merge if it looks good to you.

**Comment by metasoarous** [comment]
@eharkins Yup; Looks good. Thanks!

**Comment by eharkins** [comment]
Forgot to merge this PR with a merge commit; here is the diff from merging:
https://github.com/matsengrp/cft/compare/8c84fc01a4ab...cd947f3d435f

**Pull request closed without merging**
